Prefix: "&b[&6Duck Facts:&b] "
Timing: 20
Messages:
  - "&dDid you know, the fear that somewhere in the world, a duck is watching you is called Anatidaephobia."
  - "&aAlkali_Metal owns a duck plushie."
  - "&dA baby duck is called a duckling, and an adult male is a drake. An adult female duck is called a hen or a duck, and a group of ducks can be called a raft, team, or paddling."
  - "&dAll types of ducks are part of the bird family Anatidae, which also includes swans and geese."